# V2

In [1]:
"""
Test script to try new parsing schemes/imports.
"""

from pathlib import Path

TESTDIR = Path(r"C:\Users\utrfh\WS22-23 (MA) Masterarbeit\RADC_testData\2023-10-10_Denis_NewFrames")
TESTFILE_1chan = Path(TESTDIR, "sw_trigg_frame_1ch.bin") # contain 5 software-triggers each
TESTFILE_3chan = Path(TESTDIR, "sw_trigg_frame_3ch.bin")
TESTFILE_5chan = Path(TESTDIR, "sw_trigg_frame_5ch.bin")

In [2]:
import struct
format = "< cB3sIIB B3schB 64h"

st = struct.Struct(format)
with open(TESTFILE_1chan, "rb") as file:
    filecontents = file.read()
st.unpack_from(filecontents, 0)
filecontents

b'\x00\x00\x00\x05\x00\x00\x00\x96@Q@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00?\xf0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@G\x80\x00\x00\x00\x00\x00@S\x00\x00\x00\x00\x00\x00@N\x00\x00\x00\x00\x00\x00@\x08\x00\x00\x00\x00\x00\x00@\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00?\xf0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@o\xc0\x00\x00\x00\x00\x00@o\xe0\x00\x00\x00\x00\x00@.\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@e\x00\x00\x00\x00\x00\x00@L\x00\x00\x00\x00\x00\x00?\xf0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@g`\x00\x00\x00\x00\x00@O\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@Q@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@E\x00\x00\x00\x00\x00\x00@B\x80\x00\x00\x00\x00\x00@9\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@7\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00?\xf0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@d`\x00\x00\x00\x00\x00@1\x00\x00\x00\x00\x00\x00?\xf0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@g\xa0\x00\x00\x00\x00\x00@O\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@Q@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@e\x80\x00\x00\x00\x00\x00@i\x80\x00\x00\x00\x00\x00@^@\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@<\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00?\xf0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00?\xf0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@B\x80\x00\x00\x00\x00\x00@g \x00\x00\x00\x00\x00?\xf0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@g\x80\x00\x00\x00\x00\x00@O\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@Q@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@2\x00\x00\x00\x00\x00\x00@_\x00\x00\x00\x00\x00\x00@W\x00\x00\x00\x00\x00\x00?\xf0\x00\x00\x00\x00\x00\x00@A\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00?\xf0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@o\xa0\x00\x00\x00\x00\x00@o\xe0\x00\x00\x00\x00\x00@.\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@a`\x00\x00\x00\x00\x00@Z\x00\x00\x00\x00\x00\x00?\xf0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@g\x80\x00\x00\x00\x00\x00@O\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@Q@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@n\x00\x00\x00\x00\x00\x00@>\x00\x00\x00\x00\x00\x00@c\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@C\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00?\xf0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@Z@\x00\x00\x00\x00\x00@&\x00\x00\x00\x00\x00\x00?\xf0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00

In [3]:
# data_parser is installed on the system
import data_parser
data_parser.init("v2")
from data_parser import struct_conversion, data_io, plotting
# from data_parser.configuration import CONFIG

Imported struct_conversion v2

In [4]:
file = TESTFILE_1chan
datafile = struct_conversion.DataFile(file, tracelength=64, endianness="little-endian", include_UDP_header=False)
print(datafile.format)
list(datafile.get_records())

('<  cB3sIIB', '< B3schB hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh')
(b'\x00', 0, b'\x00\x05\x00', 1083572224, 16465, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 1280, 'Seconds': 1083572224, 'Subsecs': 16465, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 15744768, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 15744768, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 2152153088, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 2152153088, 'Subsecs': 0, 'Snippet_count': 0}
(b'@', 83, b'\x00\x00\x00', 1073741824, 78, 0)
Init header with tuple {'Trigger_type': '@', 'Frame_number': 83, 'Event_ID': 0, 'Seconds': 1073741824, 'Subsecs': 78, 'Snippet_count': 0}
(b'\x00', 0, b'@\x08\x00', 0, 1327104, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 2112, 'Seconds': 0, 'Subsecs': 1327104, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'?', 240, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '?', 'Frame_number': 240, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'@o\xc0', 0, 3765387264, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 12611392, 'Seconds': 0, 'Subsecs': 3765387264, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00@', 46, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 4194304, 'Seconds': 46, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 6635520, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 6635520, 'Subsecs': 0, 'Snippet_count': 0}
(b'@', 76, b'\x00\x00\x00', 1056964608, 240, 0)
Init header with tuple {'Trigger_type': '@', 'Frame_number': 76, 'Event_ID': 0, 'Seconds': 1056964608, 'Subsecs': 240, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'@g`', 0, 2152677376, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 6317888, 'Seconds': 0, 'Subsecs': 2152677376, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00@', 16465, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 4194304, 'Seconds': 16465, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 16384, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 16384, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'@E\x00', 0, 2151825408, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 17728, 'Seconds': 0, 'Subsecs': 2151825408, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00@', 57, 1073741824, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 4194304, 'Seconds': 57, 'Subsecs': 1073741824, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 3620864, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 3620864, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 0, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 0, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 15744768, 0)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 15744768, 'Snippet_count': 0}
(b'\x00', 0, b'\x00\x00\x00', 0, 1073741824, 16)
Init header with tuple {'Trigger_type': '\x00', 'Frame_number': 0, 'Event_ID': 0, 'Seconds': 0, 'Subsecs': 1073741824, 'Snippet_count': 16}
(0, b'\x00\x00\x00', b'\x00', 0, 0, 0, 0, 4160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25664, 96, 0, 0, 12608, 0, 0, 0, -4033, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
Init header with tuple {'Channel_number': 0, 'Energy': 0, 'Info_flags': b'\x00', 'Timedelta_samples': 0, 'Snippet_number': 0}
(0, b'\x00\x00\x00', b'\x00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
Init header with tuple {'Channel_number': 0, 'Energy': 0, 'Info_flags': b'\x00', 'Timedelta_samples': 0, 'Snippet_number': 0}
(0, b'\x00\x00\x00', b'\x00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
Init header with tuple {'Channel_number': 0, 'Energy': 0, 'Info_flags': b'\x00', 'Timedelta_samples': 0, 'Snippet_number': 0}
(0, b'\x00\x00\x00', b'\x00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
Init header with tuple {'Channel_number': 0, 'Energy': 0, 'Info_flags': b'\x00', 'Timedelta_samples': 0, 'Snippet_number': 0}
(0, b'\x00\x00\x00', b'\x00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26432, 160, 0, 0, 20288, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
Init header with tuple {'Channel_number': 0, 'Energy': 0, 'Info_flags': b'\x00', 'Timedelta_samples': 0, 'Snippet_number': 0}
(0, b'\x00\x00\x00', b'\x00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
Init header with tuple {'Channel_number': 0, 'Energy': 0, 'Info_flags': b'\x00', 'Timedelta_samples': 0, 'Snippet_number': 0}
(0, b'\x00\x00\x00', b'\x00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
Init header with tuple {'Channel_number': 0, 'Energy': 0, 'Info_flags': b'\x00', 'Timedelta_samples': 0, 'Snippet_number': 0}
(0, b'\x00\x00\x00', b'\x00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
Init header with tuple {'Channel_number': 0, 'Energy': 0, 'Info_flags': b'\x00', 'Timedelta_samples': 0, 'Snippet_number': 0}
(0, b'\x00\x00\x00', b'@', 16465, 0, 0, 0, 0, 0, 0, 0, 2112, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25920, 128, 0, 0, 26944, 128, 0, 0, 24128, 64, 0, 0, 64, 0, 0, 0, 15424, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -4033, 0, 0, 0, 0, 0, 0, 0, -4033, 0, 0, 0, 0, 0)
Init header with tuple {'Channel_number': 0, 'Energy': 0, 'Info_flags': b'@', 'Timedelta_samples': 16465, 'Snippet_number': 0}
(0, b'\x00\x00\x00', b'\x00', 0, 0, 0, 0, 0, 0, 0, 0, 16960, 128, 0, 0, 26432, 32, 0, 0, -4033, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)

[{'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 1280,
  'Seconds': 1083572224,
  'Subsecs': 16465,
  'Snippet_count': 0,
  'Timestamp_s': 1083572224.0002635,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 15744768,
  'Snippet_count': 0,
  'Timestamp_s': 0.251916288,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 2152153088,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 2152153088.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '@',
  'Frame_number': 83,
  'Event_ID': 0,
  'Seconds': 1073741824,
  'Subsecs': 78,
  'Snippet_count': 0,
  'Timestamp_s': 1073741824.0000012,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 2112,
  'Seconds': 0,
  'Subsecs': 1327104,
  'Snippet_count': 0,
  'Timestamp_s': 0.021233664,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '?',
  'Frame_number': 240,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 12611392,
  'Seconds': 0,
  'Subsecs': 3765387264,
  'Snippet_count': 0,
  'Timestamp_s': 60.246196224,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 4194304,
  'Seconds': 46,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 46.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 6635520,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 6635520.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '@',
  'Frame_number': 76,
  'Event_ID': 0,
  'Seconds': 1056964608,
  'Subsecs': 240,
  'Snippet_count': 0,
  'Timestamp_s': 1056964608.0000038,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 6317888,
  'Seconds': 0,
  'Subsecs': 2152677376,
  'Snippet_count': 0,
  'Timestamp_s': 34.442838016,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 4194304,
  'Seconds': 16465,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 16465.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 16384,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 16384.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 17728,
  'Seconds': 0,
  'Subsecs': 2151825408,
  'Snippet_count': 0,
  'Timestamp_s': 34.429206528,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 4194304,
  'Seconds': 57,
  'Subsecs': 1073741824,
  'Snippet_count': 0,
  'Timestamp_s': 74.179869184,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 3620864,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 3620864.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 0,
  'Snippet_count': 0,
  'Timestamp_s': 0.0,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 15744768,
  'Snippet_count': 0,
  'Timestamp_s': 0.251916288,
  'length': 14,
  'snippet_space': 0,
  'snippets': []},
 {'Trigger_type': '\x00',
  'Frame_number': 0,
  'Event_ID': 0,
  'Seconds': 0,
  'Subsecs': 1073741824,
  'Snippet_count': 16,
  'Timestamp_s': 17.179869184,
  'length': 2190,
  'snippet_space': 10,
  'snippets': [{'Channel_number': 0,
    'Energy': 0,
    'Info_flags': b'\x00',
    'Timedelta_samples': 0,
    'Snippet_number': 0,
    'min': -7104,
    'max': 4160,
    'trigger_count': 0,
    'trigger_IDs': [],
    'samples': [0,
     0,
     4160,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     -7104,
     96,
     0,
     0,
     -3776,
     0,
     0,
     0,
     -4033,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0]},
   {'Channel_number': 0,
    'Energy': 0,
    'Info_flags': b'\x00',
    'Timedelta_samples': 0,
    'Snippet_number': 0,
    'min': 0,
    'max': 0,
    'trigger_count': 0,
    'trigger_IDs': [],
    'samples': [0,
     0,
     0,

In [5]:


df = data_io.datafile_to_df(datafile)
# df = data_io.make_total_dataFrame([datafile])

# plot = plotting.plot_rows(df)
df

,Trigger_type,Frame_number,Event_ID,Seconds,Subsecs,Snippet_count,Timestamp_s,length,snippet_space,snippets,Datetime
0, ,0,1280,1083572224,16465,0,1.083572e+09,14,0,[],1970-01-01 00:00:01.083572224
1, ,0,0,0,15744768,0,2.519163e-01,14,0,[],1970-01-01 00:00:00.000000000
2, ,0,0,0,0,0,0.000000e+00,14,0,[],1970-01-01 00:00:00.000000000
3, ,0,0,2152153088,0,0,2.152153e+09,14,0,[],1970-01-01 00:00:02.152153088
4,@,83,0,1073741824,78,0,1.073742e+09,14,0,[],1970-01-01 00:00:01.073741824
...,...,...,...,...,...,...,...,...,...,...,...
102, ,0,4194304,16465,0,0,1.646500e+04,14,0,[],1970-01-01 00:00:00.000016465
103, ,0,0,1064960,0,0,1.064960e+06,14,0,[],1970-01-01 00:00:00.001064960
104, ,0,0,0,0,0,0.000000e+00,14,0,[],1970-01-01 00:00:00.000000000
105, ,0,12864,0,6242304,0,9.987686e-02,14,0,[],1970-01-01 00:00:00.000000000
106, ,0,4194304,87,1056964608,240,1.039114e+02,32654,10,"[{'Channel_number': 0, 'Energy': 0, 'Info_flag...",1970-01-01 00:00:00.000000103

In [6]:
import pandas
pandas.concat([df])

,Trigger_type,Frame_number,Event_ID,Seconds,Subsecs,Snippet_count,Timestamp_s,length,snippet_space,snippets,Datetime
0, ,0,1280,1083572224,16465,0,1.083572e+09,14,0,[],1970-01-01 00:00:01.083572224
1, ,0,0,0,15744768,0,2.519163e-01,14,0,[],1970-01-01 00:00:00.000000000
2, ,0,0,0,0,0,0.000000e+00,14,0,[],1970-01-01 00:00:00.000000000
3, ,0,0,2152153088,0,0,2.152153e+09,14,0,[],1970-01-01 00:00:02.152153088
4,@,83,0,1073741824,78,0,1.073742e+09,14,0,[],1970-01-01 00:00:01.073741824
...,...,...,...,...,...,...,...,...,...,...,...
102, ,0,4194304,16465,0,0,1.646500e+04,14,0,[],1970-01-01 00:00:00.000016465
103, ,0,0,1064960,0,0,1.064960e+06,14,0,[],1970-01-01 00:00:00.001064960
104, ,0,0,0,0,0,0.000000e+00,14,0,[],1970-01-01 00:00:00.000000000
105, ,0,12864,0,6242304,0,9.987686e-02,14,0,[],1970-01-01 00:00:00.000000000
106, ,0,4194304,87,1056964608,240,1.039114e+02,32654,10,"[{'Channel_number': 0, 'Energy': 0, 'Info_flag...",1970-01-01 00:00:00.000000103